version: '3.7'

services:
  mcserver:
    container_name: 'mcserver'
    image: 'mcserver'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "25565:25565"
    volumes:
    - ./mcserver/plugins:/opt/minecraft/plugins
    - ./mcserver/worlds:/opt/minecraft/worlds
