version: '2.4'
services:
  niscore-build:
    container_name: niscore-build
    image: adoptopenjdk/openjdk16
    working_dir: /opt/build
    entrypoint: bash -c "chmod +x ./gradlew && ./gradlew clean build"
    environment:
      GRADLE_USER_HOME: /opt/build/.gradle/caches
    volumes:
      - .:/opt/build:Z