database:
  # SQL dialect to use (supports: H2)
  dialect: H2
  # Connection mode. Can be file, mem, tcp, ssl, zip, ...
  # See https://h2database.com/html/features.html#connection_modes for all possible modes
  mode: 'file'
  # The connection to the database. This can be a file path, or a remote address.
  # Use {FILENAME} token to replace using filename option
  connection: '{FILENAME}'
  # Extra data to be appended to the URL
  extra: ''
  # Database username
  username: 'user'
  # Database password
  password: 'pass'
  # Name of the database file that will be used to store player data
  filename: @database.filename@
disconnect-memory:
  # Time (in seconds) to remember a player after they have disconnected from the server
  # This allows players to ignore other players that keep reconnecting rapidly
  forget-after: 15
ignorelist:
  # Enable the ability for players to ignore other players
  enabled: true
  # Size of each page sent to the player when they do /ignorelist
  page-size: 10
kill:
  enabled: true
whisper:
  enabled: true
permissions:
  enabled: true
  defaults:
    - space.nerdsin.enhancedchat.*
    - bukkit.command.tps