name: @name@
main: @class@
version: @version@
api-version: @apiversion@
commands:
  ignore:
    description: Hide a players messages from chat
    usage: /ignore <player name>
  unignore:
    description: Stop ignoring a players messages
    usage: /unignore <player name>
  ignorelist:
    description: Shows a list of people ignored
    usage: /ignorelist [page]
permissions:
  enhancedchat.*:
    default: false