# The X axis that a custom world spawn should originate from
# Default: 0
spawn.x: 0
# The Z axis that a custom world spawn should originate from
# Default: 0
spawn.z: 0
# The radius of the random player spawns
# Default: 500
radius: 500
# If the world should keep its original spawn point
# Default: false
original: false